@echo off

set OLD_PATH=%PATH%

set GTK_BASEPATH=C:\GTK

set RUBY_PATH=C:\ruby

rem symbole euro for ruby
set INPUTRC=%RUBY_PATH%\bin\inputrc.euro

rem option for ruby
set RUBYOPT=-rubygems


rem lib for GTK
set LIB=%GTK_BASEPATH%\lib;%GTK_BASEPATH%\bin

rem include for GTK
set INCLUDE=%GTK_BASEPATH%\INCLUDE;%GTK_BASEPATH%\INCLUDE\GTK-2.0;%GTK_BASEPATH%\INCLUDE\GLIB-2.0;%GTK_BASEPATH%\INCLUDE\PANGO-1.0;%GTK_BASEPATH%\INCLUDE\CAIRO;%GTK_BASEPATH%\INCLUDE\ATK-1.0;%GTK_BASEPATH%\INCLUDE\GTKGLEXT-1.0;%GTK_BASEPATH%\LIB\GTK-2.0\INCLUDE;%GTK_BASEPATH%\LIB\GLIB-2.0\INCLUDE;%GTK_BASEPATH%\LIB\GTKGLEXT-1.0\INCLUDE;%GTK_BASEPATH%\INCLUDE\LIBGLADE-2.0;%GTK_BASEPATH%\INCLUDE\LIBXML2;

rem path with ruby and gtk
set PATH=%RUBY_PATH%\bin;%GTK_BASEPATH%;%GTK_BASEPATH%\bin;%GTK_BASEPATH%\LIB;%OLD_PATH=%


@echo on
